include /usr/local/share/luggage/luggage.make

TITLE=DontSaveNewDocumentsToiCloud
REVERSE_DOMAIN=org.macenterprise
PACKAGE_VERSION=1.0.0
PAYLOAD=\
	pack-script-pm-postflight \
	pack-resource-DontSaveNewDocumentsToiCloud.mobileconfig \
